<a href="https://colab.research.google.com/github/ajilmathews05/AJ05/blob/main/ajil_mathews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TITANIC DATASET**

In [94]:
import numpy as np

In [95]:
import pandas as pd

In [96]:
import matplotlib.pyplot as plt
import seaborn as sns

**Reading the data**

In [97]:
df=pd.read_csv('/content/titanic_dataset (1).csv')

In [98]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [99]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [100]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**PREPROCESSING STEPS**

In [101]:
from sklearn.impute import SimpleImputer

In [102]:
simple = SimpleImputer(missing_values=np.nan, strategy='median')
missing_values = simple.fit(df[['Age']])
df[['Age']] = missing_values.transform(df[['Age']])

In [103]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [104]:
df.drop('Cabin', axis=1, inplace=True)

In [105]:
df.drop(columns=['PassengerId', 'Name', 'Ticket'], inplace=True)

In [106]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  28.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [107]:
scaler = StandardScaler()
df[['Fare']] = scaler.fit_transform(df[['Fare']])

In [108]:
label_enc = LabelEncoder()
df['Sex'] = label_enc.fit_transform(df['Sex'])

In [109]:
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

In [110]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,0,3,1,22.0,1,0,-0.502445,False,True
1,1,1,0,38.0,1,0,0.786845,False,False
2,1,3,0,26.0,0,0,-0.488854,False,True
3,1,1,0,35.0,1,0,0.420730,False,True
4,0,3,1,35.0,0,0,-0.486337,False,True
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,-0.386671,False,True
887,1,1,0,19.0,0,0,-0.044381,False,True
888,0,3,0,28.0,1,2,-0.176263,False,True
889,1,1,1,26.0,0,0,-0.044381,False,False
890,0,3,1,32.0,0,0,-0.492378,True,False

# **MODELLING**

In [120]:
from sklearn.model_selection import train_test_split

In [121]:
X = df.drop(columns=['Survived'],axis=1)
y = df['Survived']

In [123]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# **KNN and SVM Models**

In [124]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [116]:
knn = KNeighborsClassifier(n_neighbors=5)
svm = SVC(kernel='linear', C=1)

In [125]:
knn.fit(X, y)
svm.fit(X, y)

SVC(C=1, kernel='linear')

#  K-fold and stratified stratified k-fold cross validation techniques

In [126]:
from sklearn.model_selection import cross_val_score, StratifiedKFold, KFold

In [119]:
kfold = KFold(n_splits=10, random_state=42, shuffle=True)
strat_kfold = StratifiedKFold(n_splits=10, random_state=42, shuffle=True)

In [82]:
knn_kfold_scores = cross_val_score(knn, X, y, cv=kfold)
svm_kfold_scores = cross_val_score(svm, X, y, cv=kfold)

In [83]:
print("kNN k-Fold CV Average Accuracy: {:.2f}%".format(knn_kfold_scores.mean() * 100))
print("SVM k-Fold CV Average Accuracy: {:.2f}%".format(svm_kfold_scores.mean() * 100))

kNN k-Fold CV Average Accuracy: 77.88%
SVM k-Fold CV Average Accuracy: 78.56%

In [84]:
knn_strat_scores = cross_val_score(knn, X, y, cv=strat_kfold)
svm_strat_scores = cross_val_score(svm, X, y, cv=strat_kfold)

In [85]:
print("kNN Stratified k-Fold CV Average Accuracy: {:.2f}%".format(knn_strat_scores.mean() * 100))
print("SVM Stratified k-Fold CV Average Accuracy: {:.2f}%".format(svm_strat_scores.mean() * 100))

kNN Stratified k-Fold CV Average Accuracy: 76.88%
SVM Stratified k-Fold CV Average Accuracy: 78.67%